// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikcihbmjvytmnlvzhsnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrY2loYm1qdnl0bW5sdnpoc25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjI1ODMsImV4cCI6MjA2ODczODU4M30.1oeDR3B7r7lTrubVK2bvYeTB6SiZaI1RYDM-k7G9NgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});